### ISSUE TITLE
[JOSS Review] Version Number

### ISSUE THREAD

**Issue by seankross** [lumenlearning/rise#1]
The CRAN version number and the version number in the DESCRIPTION file both match (which is good) however they do not match the latest GitHub release.

(https://github.com/openjournals/joss-reviews/issues/846)

**Comment by kalendar** [comment]
Sean, what's the best way to resolve this problem?

**Comment by leeper** [comment]
You can create a new release by running:

```bash
git tag -a [VERSION NUMBER] -m [VERSION NUMBER]
git push --tags
```

And editing the release/tag in the Github interface.

**Comment by kalendar** [comment]
I'm sorry I wasn't clear in my previous comment. I know how to create a new release on GitHub. But even if I were to create a new release, the CRAN version and the latest GitHub release still wouldn't match? Is the goal to have the CRAN release and GitHub release be the same? In which case, I need to submit the updated version to CRAN? Or is there a different goal? Apologies for being a little slow on the uptake here.

**Comment by leeper** [comment]
For JOSS, we want GitHub to be up to date so that when you make an archive of the repo at the end of the review process, that release matches what's gone through JOSS review. You can do this as the last stage of the review process. 

A workflow I recommend is to make a GitHub release for every version that goes to CRAN so that it's easy to map CRAN releases back to GitHub commits. But ultimately what's on CRAN is not important from the JOSS perspective, though obviously you probably will update that once the JOSS review is complete.
